# Generated by Django 5.1.5 on 2025-01-28 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_district_municipality_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='cart.state'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipality',
            name='municipality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='cart.district'),
            preserve_default=False,
        ),
    ]
