# Generated by Django 5.1.5 on 2025-01-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_deliveryaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='local_address',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
