# Generated by Django 5.1.5 on 2025-01-28 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_deliveryaddress_local_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cart.deliveryaddress')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cart.cartproduct')),
            ],
        ),
    ]
